name: k_util
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  
  provider: ^6.0.3
  get_it: ^7.2.0
  intl: 
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3
  flutter_local_notifications: ^17.2.2
  connectivity_plus: ^5.0.1
  package_info_plus: ^4.2.0
  store_redirect: ^2.0.1
  secure_shared_preferences: ^0.0.4
  badges: ^2.0.3
  uuid: ^3.0.6
  transparent_image: ^2.0.0
  sliver_tools: ^0.2.8
  url_launcher: ^6.3.0
  cached_network_image: ^3.2.1
  animated_state_widget:
    git:
      url: https://github.com/abdullahkaracabey/animated-state-widget.git

  enum_to_string: ^2.0.1
  image_picker: ^0.8.6
  webview_flutter: ^4.4.2
  dots_indicator: ^2.1.0
  path_provider: ^2.0.11
  app_settings: ^5.1.1
  flutter_multi_formatter: ^2.11.1
  get: ^4.6.5
  app_version_update: ^2.0.3
  collection: ^1.17.2
  http_parser: ^4.0.2
  universal_io: ^2.2.2
  dio: ^5.6.0
  
  
  
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # Enable generation of localized Strings from arb files.
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
